### ISSUE TITLE
Dealing with multiple associations

### ISSUE THREAD

**Issue by Bondifrench** [sequelize/express-example#17]
I have asked a question in the main `sequelize` github, but as I am using the structure that is displayed in the express-example with a slightly older version of `index.js`, I tought it might be appropriate to reference it here: [#3736](https://github.com/sequelize/sequelize/issues/3736)

**Comment by sdepold** [comment]
Isn't the question answered already?

**Comment by Bondifrench** [comment]
Yes, sorry, thanks
