### ISSUE TITLE
Wrong API on migrations

### ISSUE THREAD

**Issue by andymaster01** [sequelize/express-example#28]
Hi, I'm just starting with Sequelize, and looks like a great library!.

Using the sample project, just found out that the migrations API used is not correct, I guess is something still not migrated since the project start using umzug (I suppose)

file: 20141003120222-create-user.js

Current (wrong) API:

```javascript
up: function(migration, DataTypes, done) {
    migration
      .createTable('Users', {
        username: DataTypes.STRING
      })
      .complete(done)
  },
```

Expected (correct) API:

```javascript
up: function(queryInterface, Sequelize) {
    queryInterface
      .createTable('Users', {
        username: Sequelize.STRING
      });
  },
```

If needed, I can create the pull request with the changes.

Again, great work guys, kudos!!

**Comment by sushantdhiman** [comment]
Fixed in #29
