### ISSUE TITLE
Migrations and model syncing

### ISSUE THREAD

**Issue by badsyntax** [sequelize/express-example#32]
Hey there. Thanks for the project. Can you explain why you have both migrations for setting up table schema and model syncing? 
Thanks!

**Comment by rwoody** [comment]
The generated migrations are a side effect of running the model generation command:

```
node_modules/.bin/sequelize model:create --name User --attributes username:string
```

I use sync for unit/integration tests (to reset the database before each test), and I [would] use migrations for my development environment.

**Comment by sushantdhiman** [comment]
@badsyntax Fro two reason

1. To demonstrate new users its possible to automatically build tables and use migrations
2. Sync is useful when deploying to heroku, you wont have to run migration manually

Hope this explains reason for using both features, Also note `sync` will only create tables which are missing ( without `force` option), so its safe to use them with migrations.
