### ISSUE TITLE
Add Heroku defaults

### ISSUE THREAD

**Issue by izelnakri** [sequelize/express-example#4]
Please change models/index.js to intelligently integrate to heroku production database as default in production environment without any tweaks.

```
 heroku addons:add heroku-postgresql:dev 
```
By just typing this code to the command line production app should intelligently connect to the database. Is there any good examples of this? I've found the sequelize documentation too hacky.

**Comment by sushantdhiman** [comment]
Now we pick `DATABASE_URL` from environment  variable. Fixed in #46
