### ISSUE TITLE
Fail to run on Heroku

### ISSUE THREAD

**Issue by wenwei63029869** [sequelize/express-example#40]
Hi @sdepold, I did a node app with mySql based on your app. I used the same index.js from models, so the tables will be generated automatically once server is on. It works perfectly locally. The heroku app uses ClearDB as database and the connection is find. However, it just hangs on Heroku and no table is generated. I have created a post on [Stackoverflow](http://stackoverflow.com/questions/38691834/node-with-mysql-app-doesnt-work-on-heroku). Or you can check out my [repo](https://github.com/wenwei63029869/surveysite). I could really use some help! Thanks!!!

**Comment by sushantdhiman** [comment]
Hopefully fixed in #46 :fire:
