### ISSUE TITLE
I don't know create api is fail 

### ISSUE THREAD

**Issue by yaodehaung** [sequelize/express-example#42]
![2016-08-06 9 56 31](https://cloud.githubusercontent.com/assets/8554998/17454053/320e82e2-5bbc-11e6-98cb-af33b36655d4.png)

**Comment by sushantdhiman** [comment]
@yaodehaung Did you changed any thing from example, These url should be like `/users/create`

**Comment by sushantdhiman** [comment]
I have tested API, it works. You will need to tell me if you changed anything to uncover any possible issue behind it.
