### ISSUE TITLE
ES5 syntax

### ISSUE THREAD

**Issue by Anomnimel** [sequelize/express-example#53]
It's almost 2017, why all still use ES5 syntax?

**Comment by sushantdhiman** [comment]
I dont want to include `babel` stuff in example repository. We can consider `Node v4.0` as base and use all ES6 features available in it.

**Comment by willin** [comment]
but the officical version is up to 6.10 and 8.0 is on the road.

**Comment by ryanburnette** [comment]
It's 2018, but why use ES6?

**Comment by carbontwelve** [comment]
It's almost 2019 ;)

**Comment by papb** [comment]
Modern example added now, finally :tada:
