### ISSUE TITLE
Association via classMethods doesn't work

### ISSUE THREAD

**Issue by bwoodlt** [sequelize/express-example#56]
Have been unable to associate models with each other. 
`classMethods: {
    associate: (models) => {
       Users.hasMany(models.customers, {
         foreignKey: 'user_id'  
      })
    }
}`

Any idea what I'm missing?

Thanks!

**Comment by sushantdhiman** [comment]
You need to call `associate` method if you aren't using `models/index` https://github.com/sequelize/express-example/blob/master/models/index.js#L27

**Comment by bwoodlt** [comment]
Many thanks!


Have been able to fix that issue.

….
Regards
Adekunle Adetayo



On 31 January 2017 at 08:40:26, Sushant (notifications@github.com<mailto:notifications@github.com>) wrote:

You need to call associate method if you aren't using models/index https://github.com/sequelize/express-example/blob/master/models/index.js#L27
