### ISSUE TITLE
Can I ask a question?

### ISSUE THREAD

**Issue by lxiaoixi** [sequelize/express-example#58]
I want to know the file of the migrations's function

**Comment by lxiaoixi** [comment]
I want to know the function of the file migrants,and if I want to add a new attritute 
to a table,for example user table, I don't know should I change which file,/migrants/user or
models/user or both?

**Comment by ahelord** [comment]
When versioning the code both because the migration alters the model

**Comment by lxiaoixi** [comment]
Now,I konw,thanks!
