### ISSUE TITLE
Add seed data

### ISSUE THREAD

**Issue by MoezGholami** [sequelize/express-example#59]
If the purpose of this repo is providing a sample sequelize project, it will be beneficial if you add seed examples.

**Comment by fakiolinho** [comment]
Yes, i am having some nightmares trying to use Umzug in my beforeEach hooks to reset seeders. I am searching everywhere without a proper walkthrough. Regarding migrations things are quite straightforward but when it comes to seeders docs are really poor.

**Comment by papb** [comment]
Hello! We have a mini example of seeding the database with dummy data now:

https://github.com/sequelize/express-example/blob/master/express-main-example/sqlite-example-database/setup.js
