### ISSUE TITLE
Using folder controllers

### ISSUE THREAD

**Issue by ahelord** [sequelize/express-example#60]
Who think of using a structure of controllers as in this repo https://github.com/johnkariuki/bookmark
The controllers simplify the reading of the routes it gives atomicity the code

**Comment by sushantdhiman** [comment]
Our main focus here is to demonstrate how to use Sequelize with Express. How to group models together, how to use migrations and how to setup basic relationships.

We just want to give a bare minimum setup to learn working of Sequelize, how to set relations and then retrieve the data.

This project's express API is pretty basic and not that polished. Developer are free to choose any way they seem fit to manage their APIs using express, thats not our focus.
