### ISSUE TITLE
404 Not Found for new routes

### ISSUE THREAD

**Issue by yarnball** [sequelize/express-example#61]
Hi, I'm finding this very helpful :)

I am not familiar with "Jade" and would rather just explorer the queries output directly.

However, I continually get a `404 not found`.

How can I fix this?

```
router.get('/users', function(req, res) {
  models.Users.findAll({}).then(function(users) {
    res.json(users);
  });
});

``

**Comment by papb** [comment]
Closed for housekeeping purposes, let me know if you still have any issues. Make sure to check the modernized example now :tada:
