### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by shinji-sakai** [sequelize/express-example#65]
I tried to run this app, but I got the following error:

npm ERR! Tell the author that this fails on your system:
npm ERR!     DEBUG=express-sequelize node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs express-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls express-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Assassin\AppData\Roaming\npm-cache\_logs\2017-07-08T12_15_35_797Z-debug.log

what's the reason?
I hope you would solved to this problem.

Thanks,
Shinji

**Comment by scutler19** [comment]
Can you copy and paste the whole error log you're getting? If you scroll up on your console there should be much more info on what's breaking.

**Comment by n-davis** [comment]
I'm also having this problem.

**Comment by gaspaonrocks** [comment]
Ok so i got it to work

check out [here](https://stackoverflow.com/questions/26262196/debug-is-not-a-recognized-command-express)

the last answer makes you type a command that will run your server

Although i don't know how to set a env variable, it works for me...

**Comment by papb** [comment]
Closed for housekeeping purposes, let me know if you still have any issues. Make sure to check the modernized example now :tada:
