### ISSUE TITLE
Why export Sequelize?

### ISSUE THREAD

**Issue by psaeuerl** [sequelize/express-example#69]
I currently do not understand why Sequelize is exported in ./models/index.cs

```
db.Sequelize = Sequelize;

module.exports = db;
```

I do not see it used anywhere and from my current understanding, i do not know why it is exported here.
PS: I´m quite new to sequelize and i´m trying to understand the sample.

Thanks in advance

**Comment by sushantdhiman** [comment]
You can get static methods like `literal`, `and`, `fn` etc which will be used when building queries, It also expose errors which can be accessed like `db.Sequelize.UniqueConstraintError ` to catch errors

**Comment by psaeuerl** [comment]
Ahh thank you, this makes sense.
So it is basically best-practice (if only one database is used) to export sequelize with it.
Is the statement above valid?

**Comment by sushantdhiman** [comment]
If you need those methods or errors you can get them from `model.sequelize.Sequelize.fn` etc but thats too long for some guys. So its just a way to easily access required methods / errors

Its all up to you how you want to access it, shorter simpler way is better I guess
