### ISSUE TITLE
More documenation!

### ISSUE THREAD

**Issue by AdityaAnand1** [sequelize/express-example#70]
As a node beginner, it's not immediately clear to me why things are the way they are in this repo. I would love some explanations behind these architectural decisions :)

**Comment by gaspaonrocks** [comment]
I have a very basic app that runs node/express, minimal frontend (html/css/Js) and sequelize to create, list and delete object.

I also commented everything to make it as clear as possible.

Let me know if you're interested.

**Comment by AdityaAnand1** [comment]
Yes please!

**Comment by gaspaonrocks** [comment]
Well you can check/clone my repo @ github.com/gaspaonrocks/simple-sequelize.

Feel free to comment and/or add anything. 

Hope it helps you :-)

**Comment by papb** [comment]
Hello! Sorry to take so long. Modern example created with Sequelize v6, finally :tada: The code is commented, please let me know if you have any questions.
