### ISSUE TITLE
Starter kit not suited for newbies

### ISSUE THREAD

**Issue by gaspaonrocks** [sequelize/express-example#73]
I write something here in hope that someone reads it.

I'm fairly new to developping in general, but I'm able to learn on my own.

Anyway it was a really difficult task for me to learn how to use sequelize for several reasons. The 'getting started' link in the docs never allowed me to get started... Then i came across the express-example that i had to debug for 3 days to really understand how everything worked.

What i'm getting at is this : i have written a very minimalist app to help understand how sequelize work with node/express and very minimal frontend (html/css/js). I also commented to explain everything inside. I hope to share it with everyone if they're interested.

The express example is very hard to understand, not to mention that jade is deprecated (as it is said during the npm install). And i'm sure that like me a lot of people learn frontend development, then backend (node in our case) so they never heard of jade/pug/ejs/ember templating. I didn't learn any of them and I just checked an article saying that AoT compilation tend to make server side templating less important...

In no way i am saying that the work put in the sequelize docs or the express-example is bad, maybe not tailored to people trying node/express/sql for the first time.

Thanks for reading.

**Comment by papb** [comment]
Hi @gaspaonrocks, I know several years have passed now but just to give an update for you and anyone that happen to stumble upon this:

* Last year I basically rewrote the entire sequelize manuals from scratch, paying more attention to the Getting Started section. If you feel like, please [take a look](https://sequelize.org/master/manual/getting-started.html)! I want Sequelize to be welcome to beginners, so if you still have any other comments or questions, please feel free to ask me.
* I have just rewritten the example repository from scratch. The old express-example no longer exists. Please take a look at the new example!

**Comment by gaspaonrocks** [comment]
Hi @papb it has been a few years indeed. And going back I now understand how the example was conceived.

I'll check out the new version of sequelize. Thanks for the update.
