### ISSUE TITLE
"node_modules/.bin/sequelize" is not work on windows

### ISSUE THREAD

**Issue by hbdoy** [sequelize/express-example#75]
It will show 'node_modules' is not an internal or external command, an executable program, or a batch file.

The solution is replace `/` to `\`

**Comment by ccoenen** [comment]
Or you could put it in double quotes.

![grafik](https://user-images.githubusercontent.com/124909/47952528-2e8b9c00-df71-11e8-93d5-51d7c1a44a0d.png)

**Comment by papb** [comment]
If anyone stumbles into this again, you can just use `npx sequelize` instead of `node_modules/.bin/sequelize`. Read more about [npx](https://github.com/npm/npx#npx1----execute-npm-package-binaries). It comes with Node by default in the most recent versions.
