### ISSUE TITLE
how to use DataType from req.body

### ISSUE THREAD

**Issue by ninjasun** [sequelize/express-example#88]
Hi all, I'm struggling around that thing. Basically, in my sql table, I have FLOAT and other types and in my `req.body` all the value are string (even 'null') as they should be. Can't figure out a way to convert them before call `model.update`. `JSON.parse(req.body)` breaks everything.

My request configuration comes from:

```js
app.use(bodyParser.json());

app.use(bodyParser.urlencoded({
  extended: true
}));
app.use(fileUpload());
```

Thanks for any suggestion.

**Comment by ikhsanalatsary** [comment]
You don’t need `JSON.parse(req.body)` because it handle by body parser.

**Comment by papb** [comment]
What @ikhsanalatsary said is correct (thanks!). You shouldn't have to do `JSON.parse`.

I will close this issue for housekeeping purposes, but @ninjasun let me know if you have any further issues. Thanks!
