### ISSUE TITLE
Update this repo

### ISSUE THREAD

**Issue by IgorSzymanski** [sequelize/express-example#98]
The current implementation in this repository could be improved to enable better intellisense based on TypeScript, especially the `sequelize.import` usage in this file:

https://github.com/sequelize/express-example/blob/master/models/index.js

**Comment by markjackson02** [comment]
Perhaps you can recommend a better way of doing it (or create new PR / repo). I'm using it and it works fine. Not everyone using Sequelize is using TypeScript.

**Comment by papb** [comment]
Hello, this repository is indeed quite outdated, I agree with that. I will see what I can do.

**Comment by papb** [comment]
#99
